### ISSUE TITLE
E1 [Validator] - Test Authentication

### ISSUE THREAD

**Issue by damikael** [AgID/spid-oidc-check-op#11]
Come per #4, per i test relativi all'Autentication endpoint
https://docs.google.com/document/d/1GbYAKJbqaFSxW4RK5cJwbYU0sPAB5wZT

**Comment by FedericoFanara92** [comment]
PR with Unit Test files open at #19

**Comment by damikael** [comment]
Rilasciato con la v.1.11.0 #40
