### ISSUE TITLE
E1 [Validator] - Test Token

### ISSUE THREAD

**Issue by damikael** [AgID/spid-oidc-check-op#12]
Come per https://github.com/AgID/spid-oidc-check-op/issues/4, per i test relativi al Token endpoint
https://docs.google.com/document/d/1ioqg-uRa0CM80UGIth3H6NXXFY4J6cnj

**Comment by FedericoFanara92** [comment]
PR with Unit Test files open at #18

**Comment by damikael** [comment]
Rilasciato con la v.1.11.0 #40
