### ISSUE TITLE
test 1.2.4 - this.notes is not a function

### ISSUE THREAD

**Issue by damikael** [AgID/spid-oidc-check-op#23]
this.notes is not a function

_Originally posted by @damikael in https://github.com/AgID/spid-oidc-check-op/pull/9#discussion_r1188886439_

**Comment by FedericoFanara92** [comment]
PR aperta: #25

**Comment by damikael** [comment]
PR #25 unita su branch dev.

**Comment by damikael** [comment]
Risolto
