### ISSUE TITLE
problem compiling server npm run build 

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [AgID/spid-oidc-check-op#3]
trying compiling the server get hangs with errors

cd server && npm i && cd ..

i attach complete log error and package.json

840 error make: *** [better_sqlite3.target.mk:125: Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
840 error gyp ERR! build error 
840 error gyp ERR! stack Error: `make` failed with exit code: 2
840 error gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
840 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
840 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
840 error gyp ERR! System Linux 5.4.0-128-generic
840 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
840 error gyp ERR! cwd /home/ulukai/spid-oidc-check-op/src/server/node_modules/better-sqlite3
840 error gyp ERR! node -v v16.17.0
840 error gyp ERR! node-gyp -v v9.0.0
840 error gyp ERR! not ok
841 verbose exit 1

[2022-10-20T11_23_58_185Z-debug-0.log](https://github.com/AgID/spid-oidc-check-op/files/9829295/2022-10-20T11_23_58_185Z-debug-0.log)
[package.json.txt](https://github.com/AgID/spid-oidc-check-op/files/9829681/package.json.txt)

**Comment by damikael** [comment]
try to use node.js v12
or to upgrade better-sqlite to v7.4
